version: "3.2"
services:
  api:
    build:
      dockerfile: "backend/docker/Dockerfile.prod"
      context: .
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
