version: "3.2"
services:
  api:
    build:
      dockerfile: "backend/docker/Dockerfile.dev"
      context: .
    user: "node"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - API_PORT=3000
      - FRONTEND_PORT=8080
      - API_ENDPOINT=http://api:3000
      - JWT_SECRET_STRING=secret_string
      - MONGO_URL=mongodb://mongodb:27017/db-interface
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    stdin_open: true
    tty: true
  frontend:
    build:
      dockerfile: "frontend/docker/Dockerfile.dev"
      context: .
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
  mongodb:
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017
volumes:
  mongodata:
