version: "3.2"
services:
  api-prod:
    build:
      dockerfile: "backend/docker/Dockerfile.prod"
      context: .
    ports:
      - ${API_PORT}:${API_PORT}
    env_file:
      - .env
    depends_on:
      - mongodb
  frontend-prod:
    build:
      dockerfile: "frontend/docker/Dockerfile.prod"
      context: .
    env_file:
      - .env
    ports:
      - ${FRONTEND_PORT}:8080
  mongodb:
    image: mongo
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
