version: "3.2"
services:
  api-dev:
    build:
      dockerfile: "backend/docker/Dockerfile.dev"
      context: .
    user: "node"
    env_file:
      - .env.dev
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:${API_PORT}
    depends_on:
      - mongodb
    stdin_open: true
    tty: true
  frontend-dev:
    build:
      dockerfile: "frontend/docker/Dockerfile.dev"
      context: .
    env_file:
      - .env.dev
    ports:
      - 8095:8080
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
  mongodb:
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017
volumes:
  mongodata:
