name: db-interface

on: push

jobs:
  build_api:
    name: Build API image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build docker image
      run: docker image build -t db-interface-api -f backend/docker/Dockerfile.prod .

  build_frontend:
    name: Build frontend image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Add env to ./frontend/.env
      run: echo "VUE_APP_API_ENDPOINT=http://5.53.124.45:3000" > ./frontend/.env
    - name: Build docker image
      run: docker image build -t db-interface-frontend -f frontend/docker/Dockerfile.prod .

  check_eslint:
    name: Check ESLint problems
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install ESLint and plugins
      run: npm install eslint github:codex-team/eslint-config babel-eslint eslint-plugin-vue
    - name: Start ESlint
      uses: stefanoeb/eslint-action@master
      with:
        args: . --ext .js --ext .vue

on:
  push:
    branches:
      - stage

jobs:
  push_docker_api:
    name: Push API image
    runs-on: ubuntu-latest
    needs: build_api

    steps:
      - uses: actions/checkout@v1
      - name: Push docker image
        run: docker tag db-interface-api dhcenter/db-interface-api:stage
        run: docker push dhcenter/db-interface-api:stage

  push_docker_frontend:
    name: Push frontend image
    runs-on: ubuntu-latest
    needs: build_frontend

    steps:
      - name: Push docker image
        run: docker tag db-interface-frontend dhcenter/db-interface-frontend:stage
        run: docker push dhcenter/db-interface-frontend:stage
